# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tom Seldon
email: tom@tomseldon.co.uk
description: > # this means to ignore newlines until "baseurl:"
  I'm Tom Seldon, a web developer from Cardiff South Wales. 
  I love creating awesome stuff using frameworks such as Angular, AngularJS, React, etc. 
  although I'm equally happy working with vanilla Javascript (or TypeScript).
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.tomseldon.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: TomSeldon1
github_username: TomSeldon
google_analytics: UA-37236945-1

permalink: /blog/:title/

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - bin
  - node_modules
  - CNAME
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - tsconfig.json
  - webpack.config.js
